name = "komment"
main = "build/index.js"
compatibility_date = "2026-05-14"

[build]
command = "worker-build --release"

[assets]
directory = "../public"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[vars]
# GITHUB_CLIENT_ID = "..."
# GITHUB_CLIENT_SECRET = "..."
